parameters:
  - name: buildPlatform
    type: string
    default: 'Any CPU'

  - name: buildConfiguration
    type: string
    default: 'Release'

resources:
  repositories:
  - repository: templates
    type: git # git for Azure repos, github for github
    name: Fredproj/FredShared
    
steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'
    
  - task: VSBuild@1
    inputs:
      solution: '**/*.sln'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - template: codacy-dotnet-framework-code-coverage.yml@templates
    parameters:
      TestAssemblyFilter: '*Test*.dll'
      CodacyProjectPath: bortington/$(Build.Repository.Name)