parameters:
  - name: buildPlatform
    type: string
    default: 'Any CPU'

  - name: buildConfiguration
    type: string
    default: 'Release'

steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'
    
  - task: VSBuild@1
    inputs:
      solution: '**/*.sln'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - checkout: git://Fredproj/FredShared
    path: shared-workflows

  - template: ${{variables['System.DefaultWorkingDirectory']}}/shared-workflows/codacy-dotnet-framework-code-coverage.yml@self
    parameters:
      TestAssemblyFilter: '*Test*.dll'
      CodacyProjectPath: bortington/$(Build.Repository.Name)