      
resources:
  repositories:
  - repository: templates
    type: git # git for Azure repos, github for github
    name: Fredproj/FredShared

jobs:
  - job: Bert
    pool:
      vmImage: 'windows-latest'
    steps:      
      - template: build.yml
        parameters:
          templatesRepo: templates
      - script: |
            echo "Test: ${{ secrets.CODACY_API_TOKEN }}"
