parameters:
  - name: BuildConfiguration
    type: string
    displayName: Build configuration for running tests
    default: 'release'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
  - job: Bert
    steps:
      - task: NuGetToolInstaller@1
      
      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'
          
      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

      - template: codacy-dotnet-framework-code-coverage.yml@templates
        parameters:
          TestAssemblyFilter: '*Test*.dll'
          CodacyProjectPath: bortington/$(Build.Repository.Name)