name: 1.0.0$(Rev:.r)
trigger:
- master
- feature/*

pool:
  vmImage: 'windows-2022'

resources:
  repositories:
  - repository: templates
    type: git # git for Azure repos, github for github
    name: Fredproj/FredShared

variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

jobs:
  - job: Bert
    steps:
      - task: NuGetToolInstaller@1
      
      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'
          
      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

      - template: codacy-dotnet-framework-code-coverage.yml@templates
        parameters:
          TestAssemblyFilter: '*Test*.dll'
          CodacyProjectPath: bortington/$(Build.Repository.Name)